# ENVIRONMENT PARAMETERS

xCoordRange:
  - 100 # X start
  - 195 # X end

yCoordRange:
  - 22 # Y start
  - 65 # Y end

zCoordRange:
  - 25 # Z start
  - 25 # Z end

xThin: 1
yThin: 1
zThin: 1

# AGENT PARAMETERS

energy: 100 #Wh
velocity: 1000 #m/timeUnit
num_agents: 3
start_loc: # approx starting loc
  - 0 #X
  - 60000 #Y
  - 25 #z

# TASK PARAMETERS

tasks:
  - 0: # Task ID
      loc: 
        - -80000 #X
        - 60000 #Y
        - 25 #Z
      work: 10

  - 1: # Task ID
      loc: 
        - -40000 #X
        - 65000 #Y
        - 25 #Z
      work: 10

  - 2: # Task ID
      loc: 
        - 40000 #X
        - 65000 #Y
        - 25 #Z
      work: 10

  - 3: # Task ID
      loc: 
        - 90000 #X
        - 60000 #Y
        - 25 #Z
      work: 10

  - 4: # Task ID
      loc: 
        - -80000 #X
        - 100000 #Y
        - 25 #Z
      work: 10

  - 5: # Task ID
      loc: 
        - -40000 #X
        - 100000 #Y
        - 25 #Z
      work: 10

  - 6: # Task ID
      loc: 
        - 40000 #X
        - 100000 #Y
        - 25 #Z
      work: 10

  - 7: # Task ID
      loc: 
        - 90000 #X
        - 100000 #Y
        - 25 #Z
      work: 10