# DEFINE TEST PARAMETERS

test_name: "20n6r_fails0_tasks0_30tr.csv"

trials: 30
tests: 1

viz: False

comms_max_range: 20000
comms_decay_range: 5000 # Every decay_range meters, succ prob decays by decay rate (between passengers)
# comms_decay_range_m: 50000 # passenger-mothership decay range
comms_max_succ_prob: 1.00  # % max successful messages
comms_decay_rate: 0.05 # % decay per decay range

edge_discovery_prob: 0.00 # % chance agent has at each time step for discovering random edge
new_task_prob: 0.0 #0.025 # % chance new task appears each time step
num_new_tasks: 1 # num tasks that will be added at each new task event

robot_fail_prob: 0.0 #0.025 # % chance a robot fails each time step
percent_fail: 0.0 # % of robots that will fail at fail_timestep
fail_timeStep: 0

replan_freq: 25

# == Define each type of test that will run on each test case (trial)
sim_configs:
  # - "Cent | Best"
  - "Cent | Stoch"
  - "Dist | Stoch"
  - "Hybrid1 | Stoch"
  - "Hybrid2 | Stoch"