# PROBLEM PARAMETERS

problem_size: 30
reward_range:
  - 1 # min
  - 10 # max
work_range:
  - 0 # min
  - 0 # max
c: 0.75  # variance modifier (0.05=low, 0.25=med, 0.75=high)
start: 'vs'
end: 'vg'
rob_task: "vr"

m_id: -1

basic: False

# PASSENGER PARAMETERS

num_robots: 6
support_robots: 5 # per-group support
budget: 2000 #Wh (robot energy)
energy_burn_rate: 0.01 # Wh / (m/s)
velocity: 2000 #m/timeUnit
base_loc: # approx starting/ending loc
  - -85000 #X
  - 120000 #Y
  - 25 #z


# ENVIRONMENT PARAMETERS

xCoordRange:
  - 120 # X start
  - 190 #195 # X end

yCoordRange:
  - 22 # Y start
  - 65 # Y end

zCoordRange:
  - 25 # Z start
  - 25 # Z end

xThin: 1
yThin: 1
zThin: 1
